version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:q1w2e3r4@db/hcare-final
      - FLASK_SQLALCHEMY_TRACK_MODIFICATIONS=false
      - FLASK_REDIS_URL=redis://redis?db=1&password=Shaw@0234
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: hcare-final
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: Shaw@0234
    ports:
      - "6379:6379"